lessons_level = {
    "common_core": {
        "Physics": [
            "Gravitation universelle",
            "Exemples d’actions mécaniques",
            "Le mouvement",
            "Principe d’inertie",
            "Tension d'un ressort - Poussée d'Archimède",
            "Équilibre d'un corps sous l'action de trois forces",
            "Équilibre d'un corps solide en rotation autour d'un axe fixe",
            "Moment d'un couple de forces - Moment d'un couple de torsion",
            "Courant électrique continu",
            "Tension électrique",
            "Association des conducteurs ohmiques",
            "Caractéristiques de quelque dipôles passifs",
            "Caractéristique d'un dipôle actif",
            "Transistor",
        ],
        "Chemistry": [
            "Les espèces chimiques",
            "Extraction, séparation, et identification d’espèces chimiques",
            "Synthèse d’espèces chimiques",
            "Le modèle de l'atome",
            "Géométrie de quelques molécules",
            "Classification périodique des éléments chimiques",
            "Quantité de matière",
            "Concentration molaire des espèces moléculaires en solution",
            "Modélisation des transformations chimiques – Bilan de la matière",
        ],
    },
    "1bac_experimental": {
        "Physics": [
            "Mouvement de rotation d'un corps solide non déformable autour d'un axe fixe",
            "Travail et puissance d'une force",
            "Travail et énergie cinétique",
            "Travail et énergie potentielle de pesanteur - Énergie mécanique",
            "Travail et énergie interne",
            "Énergie thermique et transfert thermique",
            "Champ électrostatique",
            "Énergie potentielle d'une charge électrique dans un champ électrique uniforme",
            "Transfert de l’énergie dans un circuit électrique - Puissance électrique",
            "Comportement global d’un circuit",
            "Champ magnétique",
            "Champ magnétique créé par un courant électrique",
            "Forces électromagnétiques",
            "Visibilité d'un objet",
            "Images formées par un miroir plan",
            "Images formées par une lentille mince convergente",
            "Quelques instruments optiques",
        ],
        "Chemistry": [
            "Pourquoi mesurer en chimie",
            "Les grandeurs physiques liées à la quantité de matière",
            "Les solutions électrolytiques et les concentrations",
            "Suivi d’une transformation chimique - Bilan de la matière",
            "Mesure des quantités de matière en solution par conductimétrie",
            "Les réactions acido-basiques",
            "Les réactions d’oxydoréduction",
            "Dosages (ou titrages) directs",
            "L'expansion de la chimie organique",
            "Les molécules organiques",
            "Modification du squelette carboné",
            "Groupes caractéristiques - Réactivité",
        ],
    },
    "2bac_terminal": {
        "Physics": [
            "Ondes progressives",
            "Ondes périodiques",
            "Propagation d'une onde lumineuse",
            "Décroissance radioactive",
            "Noyau, énergie et masse",
            "Dipôle RC",
            "Dipôle RL",
            "Oscillation libre dans RLC en série",
            "Circuit (R,L,C) en série en régime forcé",
            "Ondes électromagnétiques",
            "Modulation d'amplitude",
            "Les lois de Newton",
            "La chute libre verticale d’un solide (pour sc.vie et terre)",
            "La chute verticale d’un solide (pour sc.physique et sc.m)",
            "Le mouvement d’un projectile dans un plan (pour sc.vie et terre)",
            "Les mouvements plans (pour sc.physique et sc.m)",
            "Mouvement des satellites et des planètes",
            "Mouvement de rotation d’un solide autour d’un axe fixe",
            "Système mécanique oscillant",
            "Aspects énergétiques (pour sc.vie et terre et sc.agro)",
            "Aspects énergétiques (pour sc.phy et sc.math)",
            "L’atome et la mécanique de Newton",
        ],
        "Chemistry": [
            "Les questions qui se pose le chimiste",
            "Transformations lentes et rapides",
            "Suivi temporel d’une transformation - Vitesse de réaction",
            "Transformations chimiques qui s’effectuent en deux sens",
            "État d'équilibre d'un système chimique",
            "Transformation liée à des réactions acides et bases",
            "Dosage acido-basique",
            "Évolution spontanée d'un système chimique",
            "Transformations spontanées dans les piles et production d'énergie",
            "Transformations forcées - L'électrolyse",
            "Réactions d'estérification et d'hydrolyse",
            "Contrôle de l'évolution d'un système chimique",
        ],
    },
}

