# -*- coding: utf-8 -*-

lessons_level = {
    "common_core": {
        "Physics": [
            "PC1: Gravitation universelle",
            "PC2: Exemples d’actions mécaniques",
            "PC3: Le mouvement",
            "PC4: Principe d’inertie",
            "PC5: Tension d'un ressort - Poussée d'Archimède",
            "PC6: Équilibre d'un corps sous l'action de trois forces",
            "PC7: Équilibre d'un corps solide en rotation autour d'un axe fixe",
            "PC8: Moment d'un couple de forces - Moment d'un couple de torsion",
            "PC9: Courant électrique continu",
            "PC10: Tension électrique",
            "PC11: Association des conducteurs ohmiques",
            "PC12: Caractéristiques de quelque dipôles passifs",
            "PC13: Caractéristique d'un dipôle actif",
            "PC14: Transistor",
        ],
        "Chemistry": [
            "CH1: Les espèces chimiques",
            "CH2: Extraction, séparation, et identification d’espèces chimiques",
            "CH3: Synthèse d’espèces chimiques",
            "CH4: Le modèle de l'atome",
            "CH5: Géométrie de quelques molécules",
            "CH6: Classification périodique des éléments chimiques",
            "CH7: Quantité de matière",
            "CH8: Concentration molaire des espèces moléculaires en solution",
            "CH9: Modélisation des transformations chimiques – Bilan de la matière",
        ],
    },
    "1bac_experimental": {
        "Physics": [
            "PC1: Mouvement de rotation d'un corps solide non déformable autour d'un axe fixe",
            "PC2: Travail et puissance d'une force",
            "PC3: Travail et énergie cinétique",
            "PC4: Travail et énergie potentielle de pesanteur - Énergie mécanique",
            "PC5: Travail et énergie interne",
            "PC6: Énergie thermique et transfert thermique",
            "PC7: Champ électrostatique",
            "PC8: Énergie potentielle d'une charge électrique dans un champ électrique uniforme",
            "PC9: Transfert de l’énergie dans un circuit électrique - Puissance électrique",
            "PC10: Comportement global d’un circuit",
            "PC11: Champ magnétique",
            "PC12: Champ magnétique créé par un courant électrique",
            "PC13: Forces électromagnétiques",
            "PC14: Visibilité d'un objet",
            "PC15: Images formées par un miroir plan",
            "PC16: Images formées par une lentille mince convergente",
            "PC17: Quelques instruments optiques",
        ],
        "Chemistry": [
            "CH1: Pourquoi mesurer en chimie",
            "CH2: Les grandeurs physiques liées à la quantité de matière",
            "CH3: Les solutions électrolytiques et les concentrations",
            "CH4: Suivi d’une transformation chimique - Bilan de la matière",
            "CH5: Mesure des quantités de matière en solution par conductimétrie",
            "CH6: Les réactions acido-basiques",
            "CH7: Les réactions d’oxydoréduction",
            "CH8: Dosages (ou titrages) directs",
            "CH9: L'expansion de la chimie organique",
            "CH10: Les molécules organiques",
            "CH11: Modification du squelette carboné",
            "CH12: Groupes caractéristiques - Réactivité",
        ],
    },
    "2bac_terminal": {
        "Physics": [
            "PC1: Ondes progressives",
            "PC2: Ondes périodiques",
            "PC3: Propagation d'une onde lumineuse",
            "PC4: Décroissance radioactive",
            "PC5: Noyau, énergie et masse",
            "PC6: Dipôle RC",
            "PC7: Dipôle RL",
            "PC8: Oscillation libre dans RLC en série",
            "PC9: Circuit (R,L,C) en série en régime forcé",
            "PC10: Ondes électromagnétiques",
            "PC11: Modulation d'amplitude",
            "PC12: Les lois de Newton",
            "PC13: La chute libre verticale d’un solide (pour sc.vie et terre)",
            "PC14: La chute verticale d’un solide (pour sc.physique et sc.m)",
            "PC15: Le mouvement d’un projectile dans un plan (pour sc.vie et terre)",
            "PC16: Les mouvements plans (pour sc.physique et sc.m)",
            "PC17: Mouvement des satellites et des planètes",
            "PC18: Mouvement de rotation d’un solide autour d’un axe fixe",
            "PC19: Système mécanique oscillant",
            "PC20: Aspects énergétiques (pour sc.vie et terre et sc.agro)",
            "PC21: Aspects énergétiques (pour sc.phy et sc.math)",
            "PC22: L’atome et la mécanique de Newton",
        ],
        "Chemistry": [
            "CH1: Les questions qui se pose le chimiste",
            "CH2: Transformations lentes et rapides",
            "CH3: Suivi temporel d’une transformation - Vitesse de réaction",
            "CH4: Transformations chimiques qui s’effectuent en deux sens",
            "CH5: État d'équilibre d'un système chimique",
            "CH6: Transformation liée à des réactions acides et bases",
            "CH7: Dosage acido-basique",
            "CH8: Évolution spontanée d'un système chimique",
            "CH9: Transformations spontanées dans les piles et production d'énergie",
            "CH10: Transformations forcées - L'électrolyse",
            "CH11: Réactions d'estérification et d'hydrolyse",
            "CH12: Contrôle de l'évolution d'un système chimique",
        ],
    },
}
